# Generated by Django 6.0.6 on 2026-07-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_profile_base_salary_remove_profile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='admin_type',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('hr_manager', 'HR Manager'), ('it_admin', 'IT Administrator')], default='hr_manager', max_length=25),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='managed_department',
            field=models.CharField(default='All Departments Scope', max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='office_location',
            field=models.CharField(default='Main Headquarters', max_length=100),
        ),
    ]
