# Generated by Django 6.0.6 on 2026-07-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_adminprofile_admin_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='leave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_type',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('hr_manager', 'HR Manager'), ('it_admin', 'IT Administrator')], default='hr_manager', max_length=30),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='managed_department',
            field=models.CharField(default='Human Resources', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Pending Assignment', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Unassigned Staff', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Emergency Leave', 'Emergency Leave')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_status',
            field=models.CharField(choices=[('Pending', 'Pending Execution'), ('Completed', 'Settled/Completed')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Regular Employee')], default='employee', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active Personnel'), ('inactive', 'Suspended/Inactive')], default='inactive', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'work_date')},
        ),
    ]
