# Generated by Django 6.0.6 on 2026-07-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_adminprofile_office_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='admin_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'System Superadmin'), ('admin', 'Department Admin'), ('employee', 'Regular Employee')], default='employee', max_length=15),
        ),
    ]
