# Generated by Django 6.0.6 on 2026-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_remove_adminprofile_admin_type_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_clocked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='managed_department',
            field=models.CharField(default='General Operations', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Operations', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Junior Associate', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'System Superadmin'), ('admin', 'Department Admin'), ('hr_manager', 'HR Manager'), ('payroll_officer', 'Payroll Officer'), ('employee', 'Regular Employee')], default='employee', max_length=20),
        ),
    ]
