# Generated by Django 6.0.6 on 2026-07-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_attendance_clock_in_time_attendance_clock_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='processing_cycle',
            field=models.CharField(choices=[('semi_monthly', 'Semi-Monthly (1st-15th & 16th-End)'), ('bi_weekly', 'Bi-Weekly (Every Two Weeks)'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='semi_monthly', max_length=20),
        ),
    ]
