# Generated by Django 6.0.6 on 2026-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_processing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='available_leave_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='processing_cycle',
            field=models.CharField(choices=[('semi_1st_half', 'Semi-Monthly (1st to 15th)'), ('semi_2nd_half', 'Semi-Monthly (16th to End of Month)'), ('bi_weekly', 'Bi-Weekly (Every Two Weeks)'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='semi_monthly', max_length=20),
        ),
    ]
